name: revelio-assignment
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - adjusttext=1.3.0
  - affine=2.4.0
  - alembic=1.16.1
  - asttokens=3.0.0
  - attrs=25.3.0
  - blosc=1.21.6
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.2
  - contextily=1.6.2
  - contourpy=1.3.2
  - cpython=3.13.5
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - folium=0.19.7
  - fonttools=4.58.4
  - freetype=2.13.3
  - freexl=2.0.0
  - geographiclib=2.0
  - geopandas=1.1.0
  - geopandas-base=1.1.0
  - geopy=2.4.1
  - geos=3.13.1
  - geotiff=1.7.4
  - greenlet=3.2.3
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.8.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgdal-core=3.10.3
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libpng=1.6.47
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mako=1.3.10
  - mapclassify=2.9.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mercantile=1.2.1
  - minizip=4.0.10
  - mkl=2024.2.2
  - munkres=1.1.4
  - narwhals=1.42.1
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.5
  - numpy=2.3.0
  - openjpeg=2.5.3
  - openssl=3.5.0
  - optuna=4.3.0
  - packaging=25.0
  - pandas=2.3.0
  - parso=0.8.4
  - pcre2=10.45
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - platformdirs=4.3.8
  - plotly=6.1.2
  - proj=9.6.2
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyogrio=0.11.0
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.20.0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pywin32=307
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - rasterio=1.4.3
  - referencing=0.30.2
  - requests=2.32.4
  - rpds-py=0.22.3
  - scikit-learn=1.7.0
  - scipy=1.15.2
  - setuptools=80.9.0
  - shapely=2.1.1
  - six=1.17.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - sqlalchemy=2.0.41
  - sqlite=3.50.1
  - stack_data=0.6.3
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - uriparser=0.9.8
  - urllib3=2.4.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
